### ISSUE TITLE
Hello, sorry to bother you.

### ISSUE THREAD

**Issue by rabcat-zz** [Vadorequest/AAD1#4]
Your project really interests me.
I have to use Yun to collect data from sensors connected to it and communicate the data with a wireless router running openwrt. Do you know how to do it? Thanks!

**Comment by Vadorequest** [comment]
Hi, I never used openwrt.

There is a lot of documentation in our project, see
https://github.com/Vadorequest/AAD1/tree/master/Design/Documentation

I think you should take a look to the 1) and 3) in first place, you could
understand many things!

**Comment by rabcat-zz** [comment]
Wow, amazing reply speed. I'll read the documents.

**Comment by rabcat-zz** [comment]
The idea came to me that I could omit the router and connect the Android phone directly with Yun. Which part of your Android program deal with receiving data from Yun?

**Comment by Vadorequest** [comment]
The CarActivity embedded a socket connection.

https://github.com/Vadorequest/AAD1/blob/master/Android/src/com/iha/wcc/CarActivity.java
line 94

A query is sent using the `send(3 args)` method, line 593
The other `send` methods are just helpers with default values.

Basically, when `send` is called, a query (a string with sometimes params)
is added to the queue
`queriesQueueSocket`, this queue is read in another thread and queries are
sent by socket to the YUN using the wifi.

2014-03-09 13:26 GMT+01:00 rabcat notifications@github.com:

> The idea came to me that I could omit the router and connect the Android
> phone directly with Yun. Which part of your Android program deal with
> receiving data from Yun?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Vadorequest/AAD1/issues/4#issuecomment-37125785
> .

## 

Cordialement,

M. Ambroise Dhenain.

**Comment by rabcat-zz** [comment]
Many thanks, I see amazing creativity and programming ability in your program. Now I can see the string sent from Yun. I've learned a lot from your program.

**Comment by Vadorequest** [comment]
The socket connectivity is not from me, I found a tutorial on internet.
http://android.serverbox.ch/?p=1039

If you want to learn/understand more/better the code, you should take a
quick look!

Really good example that I followed and customized for my own needs.

But there is a big mistake in my program, I'm using a TCP connection, I
should have choosen a UDP instead, because of that I get many issues when
the signal is lost because the connection is broken. I choose it because in
first place I wanted the YUN be able to send back data, but I don't do it
by now. So depending on your need, be careful to choose TCP or UDP!

Except that I think the code/architecture is really good and easy to
understand, or, at least, not too difficult.

2014-03-09 14:27 GMT+01:00 rabcat notifications@github.com:

> Many thanks, I see amazing creativity and programming ability in your
> program. Now I can see the string sent from Yun. I've learned a lot from
> your program.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Vadorequest/AAD1/issues/4#issuecomment-37126928
> .

## 

Cordialement,

M. Ambroise Dhenain.
